"""Crop the approved imagegen atlases. No artwork is generated by this script."""
from pathlib import Path
from PIL import Image
from collections import deque

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(r'C:/Users/22416/.codex/generated_images/01a09b96-e2ec-7ab2-823f-77d62f48b1e2')
OUT = ROOT / 'art/ui/handmade'
OUT.mkdir(parents=True, exist_ok=True)

def remove_neighbor_fragments(piece):
    """Remove only detached fragments accidentally included from adjacent atlas cells."""
    alpha = piece.getchannel('A')
    w, h = piece.size
    pixels = bytearray(alpha.tobytes())
    visited = bytearray(w*h)
    components = []
    for start, value in enumerate(pixels):
        if value < 8 or visited[start]:
            continue
        pending = deque([start]); visited[start] = 1; component = []
        while pending:
            p = pending.popleft(); component.append(p)
            for q in (p-w, p+w, p-1 if p%w else -1, p+1 if p%w < w-1 else -1):
                if 0 <= q < w*h and not visited[q] and pixels[q] >= 8:
                    visited[q] = 1; pending.append(q)
        components.append(component)
    cutoff = max(map(len, components)) * .005
    for component in components:
        if len(component) < cutoff:
            for p in component: pixels[p] = 0
    piece.putalpha(Image.frombytes('L', (w,h), bytes(pixels)))
    return piece

def split(filename, regions, design_width=1280):
    im = Image.open(SOURCE / filename).convert('RGBA')
    assert im.getextrema()[3][0] == 0, 'Expected true transparency'
    for name, rect in regions.items():
        rect = tuple(round(v * im.width / design_width) for v in rect)
        piece = im.crop(rect)
        if name in ['basket','worktop','sea_beans','sea_bream']:
            piece = remove_neighbor_fragments(piece)
        bounds = piece.getchannel('A').getbbox()
        piece = piece.crop(bounds)
        padded = Image.new('RGBA', (piece.width + 12, piece.height + 12))
        padded.paste(piece, (6, 6))
        padded.save(OUT / (name + '.png'))

names = ['tomato','lemon','herbs','sea_beans','bread','cheese','soap','matches','star_salt','crooked_cup','hotel_307_tag','misprint_postcard','ticket_bundle','blue_stamp','sardine','sea_bream']
cols = [(0,327),(329,642),(644,943),(944,1280)]
rows = [(0,344),(346,630),(630,951),(951,1280)]
regions = {n:(cols[i%4][0],rows[i//4][0],cols[i%4][1],rows[i//4][1]) for i,n in enumerate(names)}
regions['blue_stamp']=(335,951,610,1280)
regions['sardine']=(610,1010,934,1210)
regions['sea_bream']=(934,980,1280,1280)
split('exec-72955414-025b-4d32-91e7-eec2a7f07f73.png', regions)
split('exec-58a39f87-d7bd-4c99-a375-60f7ecc2d54b.png', {'shelf':(40,20,610,668),'crates':(630,160,1280,669),'worktop':(0,680,719,1230),'basket':(701,680,1280,1280)})
split('exec-ce21d051-bad5-411f-b687-05277611263d.png', {'receipt':(160,20,485,630),'tag':(610,155,1260,550),'recipe_book':(10,665,662,1265),'rod':(676,624,1280,1280)})
print('Prepared', len(list(OUT.glob('*.png'))), 'handmade cutouts')

split('exec-da2ee9d6-bad6-4901-b674-0e8583aca6dd.png', {
    'tape_workstation':(0,15,620,606), 'photo_mat':(635,25,1280,649),
    'archive_sheet':(60,619,580,1280), 'window_frame':(660,659,1240,1280)})

split('exec-f2893df0-b204-4605-adba-6d5fd8c2d1fe.png', {
    'rod_clean':(100,20,980,637), 'float':(1125,150,1330,530),
    'tackle_mat':(40,638,1535,1000)}, design_width=1536)

# Use only the painted cloth interior, excluding the generator's unwanted halo.
Image.open(SOURCE / 'exec-37752d92-8a73-4833-9d4a-5eb762b13038.png').crop((225,210,1305,815)).save(OUT / 'tote.png')
